### ISSUE TITLE
React as View layer

### ISSUE THREAD

**Issue by jbremmer** [derbyjs/derby#487]
Folks, why wouldn't you give yourself a favor and adopt React.js as view layer?

**Comment by rdewolff** [comment]
That'd be very nice!

**Comment by enjalot** [comment]
I'll be writing up a more in depth answer for react vs. derby in the future.
For now there are two main things:
1) Derby's templating has distinct advantages over React.
Namely, Derby lets you describe your behavior in your templates rather than in your code, making it accessible to designers and collaborators who don't have the time, energy or expertise to sift through your javascript. It also makes it more straightforward to see how data is mapped to views, something that is powerful as your application gets more complex.

2) You can use Racer to power your React views if you'd like
I intend to make an example of this but would be happy if someone beat me to it. @josephg already did this with ShareJS (which powers Racer and thus Derby): https://github.com/share/ShareJS/blob/master/examples/public/react.html

**Comment by mtvillwock** [comment]
@enjalot Did you ever end up writing longform about React/Derby?
