### ISSUE TITLE
Is the project died?

### ISSUE THREAD

**Issue by maggnus** [derbyjs/derby#540]
What's the current state of this project?
MongoDB 3.0+ support?

**Comment by curran** [comment]
From what I can tell, Derby is dead, but [ShareDB](https://github.com/share/sharedb) is very much alive. Mongo support comes from [sharedb-mongo](https://github.com/share/sharedb-mongo), which I'd guess works fine with MongoDB 3.0. I'm having good luck pairing ShareDB with [NextJS](https://github.com/zeit/next.js) to re-create the feature set of Derby.

**Comment by azat-co** [comment]
@maggnus I think this is dead. I'll be pulling out of my next edition of my book Practical Node.js... let's confirm with the main maintainer @nateps, is this project dead?

**Comment by nateps** [comment]
Thanks for checking. Not dead in fact; we use it at Lever for all our applications and plan to continue doing so in the immediate future. We have not been actively making improvements, however.

As our company has grown, I now need internal support from at least one of our engineers working on it. Good news is that one of our best engineers is slated to work on it in the coming year. This has been a very long time in the making and I've been doing various maneuvers internally to make this possible.

We are going to continue working on this project, because it is such a big part of our application code base right now. It is the most practical way to improve the efficiency of our engineering team and the performance of our application. As soon as work begins, I'll be happy to share more.

**Comment by curran** [comment]
Really looking forward to Lever-supported OSS activity :+1: :tada: 

ShareDB seems to be the real differentiator with the Derby stack. IMO contributions to ShareDB itself (e.g. more examples, documentation improvements, issue tending) would be of greater lasting value than contributions to Derby. I'm happy to help as well.

**Comment by niallobrien** [comment]
Any update on this? Thanks.

**Comment by curran** [comment]
Looks to me like Derby is dead, but not ShareDB.

**Comment by niallobrien** [comment]
If Derby is dead and Meteor has abandoned Blaze in favour of React, can anyone recommend a suitable alternative framework which tries to be "universal/isomorphic"? Thanks.

**Comment by curran** [comment]
@nistormihai I do not have any Open Source example of NextJS + ShareDB. We are using that stack for https://datavis.tech.

However, if there's interest I'd be open to posting an OSS starter project. Actually we are not doing proper server side rendering at the moment, and that's something we'd like to solve. Maybe starting a new OSS project with community involvement would be a Good Thing.

**Comment by droganov** [comment]
We have a running website at https://sd.lk with isomorphic react and a
redux+immutable analog of racer working on top of shareDB.
On the backend there is a shareDB driver for graphQL.

But we don't have a time in the nearest future to document all that due to
the complete work load

**Comment by droganov** [comment]
Also mind having a look at logux
https://github.com/logux

**Comment by curran** [comment]
@droganov Maybe we can join forces and create an OSS starter project. We're also looking at developing something like a redux-based analog of Racer. I've been thinking of ways to do it, and the simplest way seems to be to take advantage of https://github.com/kbadk/json0-ot-diff , which now does full String diffs.

**Comment by droganov** [comment]
@curran we're already working on top of shareDB. Why do you want to reimplement it?

**Comment by curran** [comment]
@droganov Is your solution Open Source? If so can you please share a link to a working app that uses ShareDB with isomorphic react and the redux+immutable analog of racer? My understanding is that your solution is not public, so I cannot leverage the work. If I had access to your solution, there would be no need to reimplement it.

**Comment by droganov** [comment]
@curran yes you're right we haven't released the modules yet. because we're actually refactoring them. There is no intention to hide it, we just have no resource to maintain all those modules.

We can schedule and I will show you the details. Then we can think of having roadmaps and so on

**Comment by ksaxberg** [comment]
@droganov React + Redux + shareDB sounds like an amazing stack. I was interested in trying Derby, but given the state of the project it seems like that's not a great choice. Any update on open-sourcing that internal configuration you mentioned here?

**Comment by droganov** [comment]
@ksaxberg I can push the stack, but we don't have resource to make documentation. If anyone want's to help, let's team up. The limitation however is that sharedb is not fully compatible with GraphQL. We only implemented the minimal set of features the we use.

But are you sure you're really need text or data sync on f/e? For most applications apollographql.com could be a good choice.

**Comment by ksaxberg** [comment]
@droganov Ah, was hoping you had a nascent followup to DerbyJs going on. It looks like apollo graphql has live subscriptions for data, so that should cover most of the use cases I was considering. I was just really interested in a stack that had an OT solution baked in, but reactive data would probably be enough.

Thanks for lead!
