### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by IAkumaI** [derbyjs/derby#577]
Hello,
is there any types definions for TypeScript?

**Comment by ericyhwang** [comment]
It turns out, the trickier part of adding type definitions is the Racer Model, not Derby itself. But a lot Derby depends on Racer, so the Racer types need to be done first.

I did an initial pass at types for the Model in a fork:
https://github.com/lever/racer/blob/2eaec051b753d5793494ed7e3239bfef7d5cf6f7/lib/index.d.ts

Then, I decided that developing types in a private repo would allow for faster iteration, without worrying about breaking other people.

The private definitions are reasonably stable now, and I do want to open-source them. But I'll need to schedule some time with Nate to go over them.

**Comment by cray0000** [comment]
Hi @ericyhwang ! I looked at the code you have in the `typescript*` branches of the `lever/racer` fork and the progress you made there is just wonderful!

From the recent addition of multi-argument support to the `model.at`/`model.scope` it seems that you even figured out the way to get data-driven types without need to explicitly pass the generic type with each getter call :fire: 

Is it possible to get the sneak peak of your latest typescript-friendly version of racer? Even if it has breaking changes I would really love to test it out on one of our production codebases and contribute to polishing it for the prime time.

**Comment by craigbeck** [comment]
Derby v4 and Racer v2 now both in typescript and published with typedefs.
