### ISSUE TITLE
Upgrade dependency Racer

### ISSUE THREAD

**Issue by kolegm** [derbyjs/derby#580]
Could you **upgrade** **_Racer_** for Derby **to** the last workable **version 0.9.15**?

Now it is v0.9.0.
And as I figured out, you have improved many features inside Racer.
Would be great to get them inside of Derby.

Thanks in advance!

**Comment by ericyhwang** [comment]
The dependency in `derby` is `"racer": "^0.9.0"`, which by semver rules will pick up all patch revisions, including the latest racer@0.9.15.

With NPM, you can see what version your app has installed by running `npm ls racer`. If you still have the older version of Racer, it may be due to a package-lock.json in your app, which you can update via the normal means, e.g. `npm update`.
